# """
# Auto-generated schema definitions for the unified procurement view.
# Regenerate via gen_schema.py if the underlying view adds/removes columns.
# """

# TABLE_NAME = "purchase_unified_testing_new"

# COMMON_COLUMNS = ['Record_Type', 'PO_Number', 'PO_Item', 'PR_Number', 'PR_Item', 'PO_Plant', 'Company_Code']

# REPORT_COLUMNS = {   'GateEntry': [   'GTENTRY_Balanced_Quantity',
#                      'GTENTRY_Challan_Date',
#                      'GTENTRY_Challan_No',
#                      'GTENTRY_Created_By',
#                      'GTENTRY_Driver_Name',
#                      'GTENTRY_E_Waybill',
#                      'GTENTRY_Gate_Entry_Date',
#                      'GTENTRY_Gate_Entry_Number',
#                      'GTENTRY_Gate_Entry_Status',
#                      'GTENTRY_Gate_Exit_Time',
#                      'GTENTRY_Gate_Out_Date',
#                      'GTENTRY_Gate_Out_User',
#                      'GTENTRY_Ge_Cancel_Date',
#                      'GTENTRY_Ge_Cancel_Time',
#                      'GTENTRY_Ge_Cancelled_by',
#                      'GTENTRY_Ge_Changed_By',
#                      'GTENTRY_Ge_Changed_Date',
#                      'GTENTRY_Ge_Changed_Time',
#                      'GTENTRY_Ge_Time',
#                      'GTENTRY_Gross_Weight',
#                      'GTENTRY_Invoice_Date',
#                      'GTENTRY_Invoice_No',
#                      'GTENTRY_Line_Item_No',
#                      'GTENTRY_Lorry_receipt_no',
#                      'GTENTRY_Lr_Date',
#                      'GTENTRY_Mat_Doc_Year',
#                      'GTENTRY_Material',
#                      'GTENTRY_Material_Document',
#                      'GTENTRY_Module',
#                      'GTENTRY_Net_Weight',
#                      'GTENTRY_Order_unit',
#                      'GTENTRY_Po_qty',
#                      'GTENTRY_Received_qty',
#                      'GTENTRY_Supplier',
#                      'GTENTRY_Supplier_Name',
#                      'GTENTRY_Tare_Weight',
#                      'GTENTRY_Transporter_Name',
#                      'GTENTRY_Vehicle_Number'],
#     'ME2L': [   'ME2L_Acct_Assignment_Cat',
#                 'ME2L_Char_Desc_2',
#                 'ME2L_Char_Desc_3',
#                 'ME2L_Characteristic_Value_3',
#                 'ME2L_Currency',
#                 'ME2L_External_Sort_Number',
#                 'ME2L_Incomplete',
#                 'ME2L_Item',
#                 'ME2L_Item_Category',
#                 'ME2L_Material_Group',
#                 'ME2L_Material_Group_Description',
#                 'ME2L_No_of_Positions',
#                 'ME2L_Notified_Quantity',
#                 'ME2L_Open_Target_Quantity',
#                 'ME2L_Open_Value',
#                 'ME2L_Order_Price_Unit',
#                 'ME2L_Order_Unit',
#                 'ME2L_Outline_Agreement',
#                 'ME2L_PO_History_or_Release_Documentation',
#                 'ME2L_Package_Number',
#                 'ME2L_Price_Unit',
#                 'ME2L_Princ_Agreement_Item',
#                 'ME2L_Pur_req_Item_no',
#                 'ME2L_Purch_Doc_Category',
#                 'ME2L_Purchase_req_no',
#                 'ME2L_Purchasing_Document',
#                 'ME2L_Purchasing_Info_Record',
#                 'ME2L_Qty_Released_to_Date',
#                 'ME2L_Quantity_in_SKU',
#                 'ME2L_Quotation_Deadline',
#                 'ME2L_Release_Group',
#                 'ME2L_Release_Indicator',
#                 'ME2L_Release_State',
#                 'ME2L_Release_Strategy',
#                 'ME2L_Released_Value',
#                 'ME2L_Reqmt_Priority',
#                 'ME2L_Requirement_Urgency',
#                 'ME2L_Statistical',
#                 'ME2L_Stockkeeping_unit',
#                 'ME2L_Storage_Location',
#                 'ME2L_Target_Quantity',
#                 'ME2L_Target_Value',
#                 'ME2L_Tax_Code',
#                 'ME2L_Total_Open_Value',
#                 'ME2L_Validity_Period_End',
#                 'ME2L_Validity_Period_Start',
#                 'Meterial_Description',
#                 'Name_of_Supplier',
#                 'Net_Order_Value',
#                 'Order_Quantity',
#                 'PO_Creator_ID',
#                 'PO_Creator_Name',
#                 'PO_Date',
#                 'PO_Deletion_Indicator',
#                 'PO_Department_Name',
#                 'PO_Document_Date',
#                 'PO_Material',
#                 'PO_Material_Description',
#                 'PO_Net_Price',
#                 'PO_Plant',
#                 'Plant_Description',
#                 'Purch_Organization',
#                 'Purchasing_Doc_Type',
#                 'Purchasing_Group',
#                 'Purchasing_Group_Description',
#                 'Purchasing_Organisation_Description',
#                 'Still_to_be_delivered_qty',
#                 'Still_to_be_delivered_value',
#                 'Still_to_be_invoiced_qty',
#                 'Still_to_be_invoiced_value',
#                 'Supplying_Plant',
#                 'Supplying_id'],
#     'Material_Doc_List': [   'Cust_Ref_No',
#                              'GRN_Amount',
#                              'GRN_Date',
#                              'GRN_Days',
#                              'GRN_Gross_Value',
#                              'GRN_Mov_Type',
#                              'GRN_Net_Value',
#                              'GRN_qty',
#                              'Gate_Entry_Created',
#                              'Gate_Entry_No',
#                              'MTLST_Amt_in_Loc_Cur',
#                              'MTLST_Base_Unit_of_Measure',
#                              'MTLST_Batch',
#                              'MTLST_Consumption',
#                              'MTLST_Document_Date',
#                              'MTLST_Material',
#                              'MTLST_Material_Document',
#                              'MTLST_Movement_Type',
#                              'MTLST_Plant',
#                              'MTLST_Posting_Date',
#                              'MTLST_Purchase_Order',
#                              'MTLST_Quantity',
#                              'MTLST_Special_Stock',
#                              'MTLST_Storage_Location',
#                              'MTLST_Supplier',
#                              'MTLST_WBS_Element',
#                              'Mat_Doc',
#                              'Mat_Doc_Description',
#                              'Material_Delay_Days',
#                              'SO_Item',
#                              'Sales_Ord',
#                              'Vendor_Delivery_Date'],
#     'PO_release': [   'Created_By_Name',
#                       'POR_Amount',
#                       'POR_Current_Release_Level',
#                       'POR_Deletion_Indicator',
#                       'POR_Doc_Type_Desc',
#                       'POR_PO',
#                       'POR_PO_Doc_Type',
#                       'POR_Plant_Code',
#                       'POR_Plant_Description',
#                       'PO_Approver_L1',
#                       'PO_Approver_L1_Name',
#                       'PO_Approver_L2',
#                       'PO_Approver_L2_Name',
#                       'PO_Approver_L3',
#                       'PO_Approver_L3_Name',
#                       'PO_Approver_L4',
#                       'PO_Approver_L4_Name',
#                       'PO_Approver_L5',
#                       'PO_Approver_L5_Name',
#                       'PO_Created_By',
#                       'PO_Created_On',
#                       'PO_L1_Released_On',
#                       'PO_L2_Released_On',
#                       'PO_L3_Released_On',
#                       'PO_L4_Released_On',
#                       'PO_L5_Released_On',
#                       'PO_No_Of_Days_Approval',
#                       'PO_No_Of_Releases_Required',
#                       'PO_Release_Status'],
#     'PR2PO': [   'GRN_Flag',
#                  'P2P_Created_On',
#                  'P2P_Delivery_Date',
#                  'P2P_Department',
#                  'P2P_GRN_Quantity',
#                  'P2P_Last_Changed_On',
#                  'P2P_Material',
#                  'P2P_Material_Description',
#                  'P2P_Material_Group',
#                  'P2P_PO_Item',
#                  'P2P_PO_No',
#                  'P2P_PO_Purchasing_Group',
#                  'P2P_PO_Quantity',
#                  'P2P_PO_Rejection_Text',
#                  'P2P_PO_UOM',
#                  'P2P_PR_Creator_Name',
#                  'P2P_PR_Item',
#                  'P2P_PR_No',
#                  'P2P_PR_Quantity',
#                  'P2P_Plant',
#                  'P2P_Purchasing_Group',
#                  'P2P_Vendor',
#                  'P2P_Vendor_Name',
#                  'PR_Creator',
#                  'PR_To_PO_Days'],
#     'PR_release': [   'CFO',
#                       'CFO_Name',
#                       'HOD',
#                       'HOD_Name',
#                       'MD',
#                       'MD_Name',
#                       'PR_Created_On',
#                       'PR_Current_Release_Level',
#                       'PR_Department',
#                       'PR_Final_Release_Date',
#                       'PR_L1_Released_On',
#                       'PR_L2_Released_On',
#                       'PR_L3_Released_On',
#                       'PR_L4_Released_On',
#                       'PR_PO_Created_Flag',
#                       'PR_Plant',
#                       'PR_Rejected',
#                       'PR_Rejection_Text',
#                       'PR_Release_Status',
#                       'PR_Released',
#                       'PR_Releases_Required',
#                       'PR_no_of_days_approval',
#                       'Process_Owner',
#                       'Process_Owner_Name',
#                       'Rejected_At_Level',
#                       'VC_Chairman',
#                       'VC_Chairman_Name'],
#     'SES': [   'SES_Amount',
#                'SES_Date_of_Creation',
#                'SES_Hod_Id',
#                'SES_Hod_Name',
#                'SES_Name_of_Person',
#                'SES_Passing_Levels',
#                'SES_Release_Level',
#                'SES_Release_Status',
#                'Service_Entry_Sheet'],
#     'Sap_Purchase': [   'Commitment_item',
#                         'Funds_Center',
#                         'PR_Created_By',
#                         'PR_Deletion_Indicator',
#                         'PR_Delivery_Date',
#                         'PR_PO_Conversion_Date',
#                         'PR_Price_Unit',
#                         'PR_Processing_Status',
#                         'PR_Purch_Org',
#                         'PR_Total_Value',
#                         'Release_Date',
#                         'Requisition_date',
#                         'Requisitioner',
#                         'SAP_Acct_Assignment_Cat',
#                         'SAP_Central_Contract_Item',
#                         'SAP_Changed_On',
#                         'SAP_Closed',
#                         'SAP_Committed_Date',
#                         'SAP_Committed_Quantity',
#                         'SAP_Consumption',
#                         'SAP_Creation_Indicator',
#                         'SAP_Currency',
#                         'SAP_Deliv_Date_Category',
#                         'SAP_Deliv_Date_From',
#                         'SAP_Desired_Vendor',
#                         'SAP_Distrib_Indicator',
#                         'SAP_Document_Type',
#                         'SAP_Fixed_Vendor',
#                         'SAP_Framework_Order_Item',
#                         'SAP_GR_Processing_Time',
#                         'SAP_GUID',
#                         'SAP_Goods_Receipt',
#                         'SAP_Invoice_Receipt',
#                         'SAP_Item_Category',
#                         'SAP_Item_Of_Requisition',
#                         'SAP_Item_Settlem_Reser',
#                         'SAP_Language_Key',
#                         'SAP_Material',
#                         'SAP_Material_Group',
#                         'SAP_Min_Rem_Shelf_Life',
#                         'SAP_Name_Of_Desired_Supplier',
#                         'SAP_Name_Of_Supplier',
#                         'SAP_No_Of_Requisns',
#                         'SAP_Overall_Release_Of_Requisitions',
#                         'SAP_PReq_Processing_State',
#                         'SAP_Partial_Invoice',
#                         'SAP_Planned_Deliv_Time',
#                         'SAP_Princ_Agreement_Item',
#                         'SAP_Pur_Organanition',
#                         'SAP_Purchase_Order',
#                         'SAP_Purchase_Order_Item',
#                         'SAP_Purchase_Requisition',
#                         'SAP_Purchasing_Group',
#                         'SAP_Purgroup_Description',
#                         'SAP_Quantity_Ordered',
#                         'SAP_Quantity_Requested',
#                         'SAP_Release_Group',
#                         'SAP_Release_Indicator',
#                         'SAP_Release_Strategy',
#                         'SAP_Requirement_Priority',
#                         'SAP_Requirement_Urgency',
#                         'SAP_Reservation',
#                         'SAP_Settlement_Res_No',
#                         'SAP_Shopping_Cart_Item',
#                         'SAP_Short_Text',
#                         'SAP_Shortage_Quantity',
#                         'SAP_Storage_Location',
#                         'SAP_Supply_Source',
#                         'SAP_Supplying_Plant1',
#                         'SAP_Unit_Of_Measure',
#                         'Valuation_Price'],
#     'Vendor_PO_History': [   'VH_Acct_Assign',
#                              'VH_Company',
#                              'VH_Created_By',
#                              'VH_Created_On',
#                              'VH_Customer',
#                              'VH_Department',
#                              'VH_Doc_Type',
#                              'VH_Eff_Value',
#                              'VH_Item',
#                              'VH_Item_Cat',
#                              'VH_Material',
#                              'VH_Material_Desc',
#                              'VH_Net_Price',
#                              'VH_PO_Date',
#                              'VH_PO_No',
#                              'VH_PO_Qty',
#                              'VH_PR_Item',
#                              'VH_PR_No',
#                              'VH_PR_Qty',
#                              'VH_Plant',
#                              'VH_Requisitioner',
#                              'VH_UOM',
#                              'VH_Vendor',
#                              'VH_Vendor_Name']}

# DATE_FILTER_COLUMN = {   'GateEntry': 'GTENTRY_Gate_Entry_Date',
#     'ME2L': 'PO_Document_Date',
#     'Material_Doc_List': 'MTLST_Posting_Date',
#     'PO_release': 'PO_Created_On',
#     'PR2PO': 'P2P_Created_On',
#     'PR_release': 'PR_Created_On',
#     'SES': 'SES_Date_of_Creation',
#     'Sap_Purchase': 'Requisition_date',
#     'Vendor_PO_History': 'VH_PO_Date'}

# KEY_COLUMNS = {   'GateEntry': {   'gate_entry_no': 'GTENTRY_Gate_Entry_Number',
#                      'gate_entry_status': 'GTENTRY_Gate_Entry_Status',
#                      'material_code': 'GTENTRY_Material',
#                      'plant': None,
#                      'po_number': None,
#                      'vendor_name': 'GTENTRY_Supplier_Name'},
#     'ME2L': {   'creator_name': 'PO_Creator_Name',
#                 'department': 'PO_Department_Name',
#                 'material_code': 'PO_Material',
#                 'material_desc': 'PO_Material_Description',
#                 'plant': 'PO_Plant',
#                 'po_item': 'PO_Item',
#                 'po_number': 'PO_Number',
#                 'pr_item': 'PR_Item',
#                 'pr_number': 'PR_Number',
#                 'purchasing_group': 'Purchasing_Group',
#                 'purchasing_org': 'Purch_Organization',
#                 'vendor_name': 'Name_of_Supplier'},
#     'Material_Doc_List': {   'material_code': 'MTLST_Material',
#                              'plant': 'MTLST_Plant',
#                              'po_number': 'MTLST_Purchase_Order',
#                              'vendor_name': 'MTLST_Supplier'},
#     'PO_release': {   'company_code': None,
#                       'created_by': 'Created_By_Name',
#                       'current_level': 'PO_No_Of_Releases_Required',
#                       'plant': 'POR_Plant_Code',
#                       'po_number': 'POR_PO',
#                       'release_status': 'PO_Release_Status'},
#     'PR2PO': {   'department': 'P2P_Department',
#                  'material_desc': 'P2P_Material_Description',
#                  'plant': 'P2P_Plant',
#                  'po_number': 'P2P_PO_No',
#                  'pr_number': 'P2P_PR_No',
#                  'vendor_name': 'P2P_Vendor_Name'},
#     'PR_release': {   'current_level': 'PR_Current_Release_Level',
#                       'department': 'PR_Department',
#                       'plant': 'PR_Plant',
#                       'pr_number': 'PR_Number',
#                       'rejected_at_level': 'Rejected_At_Level',
#                       'release_status': 'PR_Release_Status'},
#     'SES': {   'person_name': 'SES_Name_of_Person',
#                'plant': None,
#                'release_status': 'SES_Release_Status',
#                'service_entry_sheet': 'Service_Entry_Sheet'},
#     'Sap_Purchase': {   'company_code': 'Company_Code',
#                         'department': 'PR_Department',
#                         'material_code': 'SAP_Material',
#                         'material_desc': 'SAP_Short_Text',
#                         'plant': 'PR_Plant',
#                         'po_number': 'SAP_Purchase_Order',
#                         'pr_number': 'SAP_Purchase_Requisition',
#                         'requisitioner': 'Requisitioner',
#                         'vendor_name': 'SAP_Name_Of_Supplier'},
#     'Vendor_PO_History': {   'company_code': 'VH_Company',
#                              'department': 'VH_Department',
#                              'material_desc': 'VH_Material_Desc',
#                              'plant': 'VH_Plant',
#                              'po_number': 'VH_PO_No',
#                              'pr_number': 'VH_PR_No',
#                              'vendor_name': 'VH_Vendor_Name'}}


# def all_columns_for_report(report: str) -> list:
#     """Every column visible/queryable for a given report: common cols + that report's own cols."""
#     return COMMON_COLUMNS + REPORT_COLUMNS.get(report, [])


# def date_filter_column(report: str) -> str:
#     return DATE_FILTER_COLUMN[report]


# def key_column(report: str, key: str):
#     """Resolve a semantic key (e.g. 'vendor_name') to the real column name for a report."""
#     return KEY_COLUMNS.get(report, {}).get(key)


# REPORT_NAMES = list(REPORT_COLUMNS.keys())



"""
Auto-generated schema definitions for the unified procurement view.
Regenerate via gen_schema.py if the underlying view adds/removes columns.
"""

TABLE_NAME = "purchase_unified_testing_new"

COMMON_COLUMNS = ['Record_Type', 'PO_Number', 'PO_Item', 'PR_Number', 'PR_Item', 'PO_Plant', 'Company_Code']

REPORT_COLUMNS = {   'GateEntry': [   'GTENTRY_Balanced_Quantity',
                     'GTENTRY_Challan_Date',
                     'GTENTRY_Challan_No',
                     'GTENTRY_Created_By',
                     'GTENTRY_Driver_Name',
                     'GTENTRY_E_Waybill',
                     'GTENTRY_Gate_Entry_Date',
                     'GTENTRY_Gate_Entry_Number',
                     'GTENTRY_Gate_Entry_Status',
                     'GTENTRY_Gate_Exit_Time',
                     'GTENTRY_Gate_Out_Date',
                     'GTENTRY_Gate_Out_User',
                     'GTENTRY_Ge_Cancel_Date',
                     'GTENTRY_Ge_Cancel_Time',
                     'GTENTRY_Ge_Cancelled_by',
                     'GTENTRY_Ge_Changed_By',
                     'GTENTRY_Ge_Changed_Date',
                     'GTENTRY_Ge_Changed_Time',
                     'GTENTRY_Ge_Time',
                     'GTENTRY_Gross_Weight',
                     'GTENTRY_Invoice_Date',
                     'GTENTRY_Invoice_No',
                     'GTENTRY_Line_Item_No',
                     'GTENTRY_Lorry_receipt_no',
                     'GTENTRY_Lr_Date',
                     'GTENTRY_Mat_Doc_Year',
                     'GTENTRY_Material',
                     'GTENTRY_Material_Document',
                     'GTENTRY_Module',
                     'GTENTRY_Net_Weight',
                     'GTENTRY_Order_unit',
                     'GTENTRY_Po_qty',
                     'GTENTRY_Received_qty',
                     'GTENTRY_Supplier',
                     'GTENTRY_Supplier_Name',
                     'GTENTRY_Tare_Weight',
                     'GTENTRY_Transporter_Name',
                     'GTENTRY_Vehicle_Number'],
        'ME2L': [    'Meterial_Description',
                    'PO_Document_Date',
                    'Purchasing_Doc_Type',
                    'Purch_Organization',
                    'Purchasing_Organisation_Description',
                    'Purchasing_Group',
                    'Purchasing_Group_Description',
                    'PO_Department_Name',
                    'PO_Plant',
                    'Plant_Description',
                    'PO_Material',
                    'PO_Material_Description',
                    'Name_of_Supplier',
                    'Order_Quantity',
                    'PO_Net_Price',
                    'Net_Order_Value',
                    'Still_to_be_delivered_qty',
                    'Still_to_be_delivered_value',
                    'Still_to_be_invoiced_qty',
                    'Still_to_be_invoiced_value',
                    'PO_Deletion_Indicator',
                    'Supplying_id',
                    'Supplying_Plant',
                    'ME2L_Acct_Assignment_Cat',
                    'ME2L_Char_Desc_2',
                    'ME2L_Char_Desc_3',
                    'ME2L_Characteristic_Value_3',
                    'ME2L_Currency',
                    'ME2L_External_Sort_Number',
                    'ME2L_Incomplete',
                    'ME2L_Item',
                    'ME2L_Item_Category',
                    'ME2L_Material_Group',
                    'ME2L_Material_Group_Description',
                    'ME2L_No_of_Positions',
                    'ME2L_Notified_Quantity',
                    'ME2L_Open_Target_Quantity',
                    'ME2L_Open_Value',
                    'ME2L_Order_Price_Unit',
                    'ME2L_Order_Unit',
                    'ME2L_Outline_Agreement',
                    'ME2L_PO_History_or_Release_Documentation',
                    'ME2L_Package_Number',
                    'ME2L_Price_Unit',
                    'ME2L_Princ_Agreement_Item',
                    'ME2L_Pur_req_Item_no',
                    'ME2L_Purch_Doc_Category',
                    'ME2L_Purchase_req_no',
                    'ME2L_Purchasing_Document',
                    'ME2L_Purchasing_Info_Record',
                    'ME2L_Qty_Released_to_Date',
                    'ME2L_Quantity_in_SKU',
                    'ME2L_Quotation_Deadline',
                    'ME2L_Release_Group',
                    'ME2L_Release_Indicator',
                    'ME2L_Release_State',
                    'ME2L_Release_Strategy',
                    'ME2L_Released_Value',
                    'ME2L_Reqmt_Priority',
                    'ME2L_Requirement_Urgency',
                    'ME2L_Statistical',
                    'ME2L_Stockkeeping_unit',
                    'ME2L_Storage_Location',
                    'ME2L_Target_Quantity',
                    'ME2L_Target_Value',
                    'ME2L_Tax_Code',
                    'ME2L_Total_Open_Value',
                    'ME2L_Validity_Period_End',
                    'ME2L_Validity_Period_Start'],
        'Material_Doc_List': [   
                            'MTLST_Amt_in_Loc_Cur',
                            'MTLST_Base_Unit_of_Measure',
                            'MTLST_Batch',
                            'MTLST_Consumption',
                            'MTLST_Document_Date',
                            'MTLST_Material',
                            'MTLST_Material_Document',
                            'MTLST_Movement_Type',
                            'MTLST_Plant',
                            'MTLST_Posting_Date',
                            'MTLST_Purchase_Order',
                            'MTLST_Quantity',
                            'MTLST_Special_Stock',
                            'MTLST_Storage_Location',
                            'MTLST_Supplier',
                            'MTLST_WBS_Element'],
        'PO_release': [   'GRN_Flag',
                        'PO_Approver_L1',
                        'PO_Approver_L1_Name',
                        'PO_L1_Released_On',
                        'PO_Approver_L2',
                        'PO_Approver_L2_Name',
                        'PO_L2_Released_On',
                        'PO_Approver_L3',
                        'PO_Approver_L3_Name',
                        'PO_L3_Released_On',
                        'PO_Approver_L4',
                        'PO_Approver_L4_Name',
                        'PO_L4_Released_On',
                        'PO_Approver_L5',
                        'PO_Approver_L5_Name',
                        'PO_L5_Released_On',
                        'PO_Created_By',
                        'Created_By_Name',
                        'PO_Created_On',
                        'PO_No_Of_Days_Approval',
                        'PO_No_Of_Releases_Required',
                        'POR_Amount',
                        'POR_Current_Release_Level',
                        'POR_Deletion_Indicator',
                        'POR_Doc_Type_Desc',
                        'POR_PO',
                        'POR_PO_Doc_Type',
                        'POR_Plant_Code',
                        'POR_Plant_Description'],
    'PR2PO': [   'PO_Date',
                'PO_Creator_ID',
                'PO_Creator_Name',
                'PO_Release_Status',
                'P2P_Created_On',
                'PR_Creator',
                'P2P_PR_Quantity',
                'PR_Release_Status',
                'PR_Rejection_Text',
                'PR_Final_Release_Date',
                'P2P_Last_Changed_On',
                'PR_To_PO_Days',
                'P2P_GRN_Quantity',
                'P2P_Delivery_Date',
                'P2P_Department',
                'P2P_Vendor',
                'P2P_Vendor_Name',
                'P2P_PO_No',
                'P2P_PO_Item',
                'P2P_PR_No',
                'P2P_PR_Item',
                'P2P_PR_Creator_Name',
                'P2P_Material',
                'P2P_Material_Description',
                'P2P_Material_Group',
                'P2P_Plant',
                'P2P_Purchasing_Group',
                'P2P_PO_Purchasing_Group',
                'P2P_PO_Quantity',
                'P2P_PO_Rejection_Text',
                'P2P_PO_UOM'],
    'PR_release': [   'PR_Current_Release_Level',
                        'PR_Releases_Required',
                        'PR_Released',
                        'PR_Rejected',
                        'Rejected_At_Level',
                        'PR_L1_Released_On',
                        'PR_L2_Released_On',
                        'PR_L3_Released_On',
                        'PR_L4_Released_On',
                        'HOD',
                        'HOD_Name',
                        'CFO',
                        'CFO_Name',
                        'MD',
                        'MD_Name',
                        'Process_Owner',
                        'Process_Owner_Name',
                        'VC_Chairman',
                        'VC_Chairman_Name',
                        'PR_PO_Created_Flag',
                        'PR_no_of_days_approval',
                        'PR_Created_On'],
    'SES': [   'SES_Amount',
               'SES_Date_of_Creation',
               'SES_Hod_Id',
               'SES_Hod_Name',
               'SES_Name_of_Person',
               'SES_Passing_Levels',
               'SES_Release_Level',
               'SES_Release_Status',
               'Service_Entry_Sheet'],
    'Sap_Purchase': [   'Requisition_date',
                        'Requisitioner',
                        'PR_Department',
                        'PR_Plant',
                        'Company_Code',
                        'PR_Purch_Org',
                        'PR_Total_Value',
                        'Valuation_Price',
                        'PR_Price_Unit',
                        'PR_Delivery_Date',
                        'PR_Deletion_Indicator',
                        'PR_Processing_Status',
                        'Release_Date',
                        'Funds_Center',
                        'Commitment_item',
                        'PR_PO_Conversion_Date',
                        'PR_Created_By',
                        'SAP_Acct_Assignment_Cat',
                        'SAP_Central_Contract_Item',
                        'SAP_Changed_On',
                        'SAP_Closed',
                        'SAP_Committed_Quantity',
                        'SAP_Committed_Date',
                        'SAP_Consumption',
                        'SAP_Creation_Indicator',
                        'SAP_Currency',
                        'SAP_Deliv_Date_From',
                        'SAP_Deliv_Date_Category',
                        'SAP_Desired_Vendor',
                        'SAP_Distrib_Indicator',
                        'SAP_Document_Type',
                        'SAP_Fixed_Vendor',
                        'SAP_Framework_Order_Item',
                        'SAP_GR_Processing_Time',
                        'SAP_GUID',
                        'SAP_Goods_Receipt',
                        'SAP_Invoice_Receipt',
                        'SAP_Item_Category',
                        'SAP_Item_Of_Requisition',
                        'SAP_Item_Settlem_Reser',
                        'SAP_Language_Key',
                        'SAP_Material',
                        'SAP_Material_Group',
                        'SAP_Min_Rem_Shelf_Life',
                        'SAP_Name_Of_Desired_Supplier',
                        'SAP_Name_Of_Supplier',
                        'SAP_No_Of_Requisns',
                        'SAP_Overall_Release_Of_Requisitions',
                        'SAP_PReq_Processing_State',
                        'SAP_Partial_Invoice',
                        'SAP_Planned_Deliv_Time',
                        'SAP_Princ_Agreement_Item',
                        'SAP_Pur_Organanition',
                        'SAP_Purchase_Order_Item',
                        'SAP_Purchase_Requisition',
                        'SAP_Purchase_Order',
                        'SAP_Purchasing_Group',
                        'SAP_Purgroup_Description',
                        'SAP_Quantity_Ordered',
                        'SAP_Quantity_Requested',
                        'SAP_Release_Group',
                        'SAP_Release_Indicator',
                        'SAP_Release_Strategy',
                        'SAP_Requirement_Priority',
                        'SAP_Requirement_Urgency',
                        'SAP_Reservation',
                        'SAP_Settlement_Res_No',
                        'SAP_Shopping_Cart_Item',
                        'SAP_Short_Text',
                        'SAP_Shortage_Quantity',
                        'SAP_Storage_Location',
                        'SAP_Supply_Source',
                        'SAP_Supplying_Plant1',
                        'SAP_Unit_Of_Measure'],
    'Vendor_PO_History': [   'GRN_qty',
                            'GRN_Amount',
                            'GRN_Net_Value',
                            'GRN_Gross_Value',
                            'Mat_Doc',
                            'Mat_Doc_Description',
                            'GRN_Mov_Type',
                            'Gate_Entry_No',
                            'Gate_Entry_Created',
                            'GRN_Date',
                            'Sales_Ord',
                            'SO_Item',
                            'Cust_Ref_No',
                            'Vendor_Delivery_Date',
                            'GRN_Days',
                            'Material_Delay_Days',
                            'VH_Acct_Assign',
                            'VH_Company',
                            'VH_Created_By',
                            'VH_Created_On',
                            'VH_Customer',
                            'VH_Department',
                            'VH_Doc_Type',
                            'VH_Eff_Value',
                            'VH_Item',
                            'VH_Item_Cat',
                            'VH_Material',
                            'VH_Material_Desc',
                            'VH_Net_Price',
                            'VH_PO_Date',
                            'VH_PO_No',
                            'VH_PO_Qty',
                            'VH_PR_Item',
                            'VH_PR_No',
                            'VH_PR_Qty',
                            'VH_Plant',
                            'VH_Requisitioner',
                            'VH_UOM',
                            'VH_Vendor',
                            'VH_Vendor_Name']}

DATE_FILTER_COLUMN = {   'GateEntry': 'GTENTRY_Gate_Entry_Date',
    'ME2L': 'PO_Document_Date',
    'Material_Doc_List': 'MTLST_Posting_Date',
    'PO_release': 'PO_Created_On',
    'PR2PO': 'P2P_Created_On',
    'PR_release': 'PR_Created_On',
    'SES': 'SES_Date_of_Creation',
    'Sap_Purchase': 'Requisition_date',
    'Vendor_PO_History': 'VH_PO_Date'}

KEY_COLUMNS = {
    'GateEntry': {
        'gate_entry_no': 'GTENTRY_Gate_Entry_Number',
        'gate_entry_status': 'GTENTRY_Gate_Entry_Status',
        'material_code': 'GTENTRY_Material',
        'plant': None,
        'po_number': 'PO_Number',
        'vendor_name': 'GTENTRY_Supplier_Name'
    },

    'ME2L': {
        'creator_name': None,
        'department': 'PO_Department_Name',
        'material_code': 'PO_Material',
        'material_desc': 'PO_Material_Description',
        'plant': 'PO_Plant',
        'po_item': 'ME2L_Item',
        'po_number': 'ME2L_Purchasing_Document',
        'pr_item': 'ME2L_Pur_req_Item_no',
        'pr_number': 'ME2L_Purchase_req_no',
        'purchasing_group': 'Purchasing_Group',
        'purchasing_org': 'Purch_Organization',
        'vendor_name': 'Name_of_Supplier'
    },

    'Material_Doc_List': {
        'material_code': 'PO_Material',
        'plant': 'PO_Plant',
        'po_number': 'ME2L_Purchasing_Document',
        'vendor_name': 'Name_of_Supplier'
    },

    'PO_release': {
        'company_code': None,
        'created_by': 'PO_Created_By',
        'current_level': 'POR_Current_Release_Level',
        'plant': 'POR_Plant_Code',
        'po_number': 'POR_PO',
        'release_status': None
    },

    'PR2PO': {
        'department': 'P2P_Department',
        'material_desc': 'P2P_Material_Description',
        'plant': 'P2P_Plant',
        'po_number': 'P2P_PO_No',
        'pr_number': 'P2P_PR_No',
        'vendor_name': 'P2P_Vendor_Name'
    },

    'PR_release': {
        'current_level': 'PR_Current_Release_Level',
        'department': 'PR_Department',
        'plant': 'PR_Plant',
        'pr_number': 'PR_Number',
        'rejected_at_level': 'Rejected_At_Level',
        'release_status': 'PR_Release_Status'
    },

    'SES': {
        'person_name': 'SES_Name_of_Person',
        'plant': None,
        'release_status': 'SES_Release_Status',
        'service_entry_sheet': 'Service_Entry_Sheet'
    },

    'Sap_Purchase': {
        'company_code': 'Company_Code',
        'department': 'PR_Department',
        'material_code': 'SAP_Material',
        'material_desc': 'SAP_Short_Text',
        'plant': 'PR_Plant',
        'po_number': 'SAP_Purchase_Order',
        'pr_number': 'SAP_Purchase_Requisition',
        'requisitioner': 'Requisitioner',
        'vendor_name': 'SAP_Name_Of_Supplier'
    },

    'Vendor_PO_History': {
        'company_code': 'VH_Company',
        'department': 'VH_Department',
        'material_code': 'VH_Material',
        'material_desc': 'VH_Material_Desc',
        'plant': 'VH_Plant',
        'po_number': 'VH_PO_No',
        'pr_number': 'VH_PR_No',
        'vendor_name': 'VH_Vendor_Name'
    }
}

def all_columns_for_report(report: str) -> list:
    """Every column visible/queryable for a given report: common cols + that report's own cols."""
    return COMMON_COLUMNS + REPORT_COLUMNS.get(report, [])


def date_filter_column(report: str) -> str:
    return DATE_FILTER_COLUMN[report]


def key_column(report: str, key: str):
    """Resolve a semantic key (e.g. 'vendor_name') to the real column name for a report."""
    return KEY_COLUMNS.get(report, {}).get(key)


REPORT_NAMES = list(REPORT_COLUMNS.keys())
